# Severe Weather Effects on Health and Property: Recent Trends

[Jeremy Shantz](https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile)

## Synopsis
describes and summarizes your analysis in at most 10 complete sentences.

Storms and other severe weather events can cause both public health and economic problems for communities and municipalities. Many severe events can result in fatalities, injuries, and property damage, and preventing such outcomes to the extent possible is a key concern.

This project involves exploring the U.S. National Oceanic and Atmospheric Administration's (NOAA) storm database. This database tracks characteristics of major storms and weather events in the United States, including when and where they occur, as well as estimates of any fatalities, injuries, and property damage.
Data

## Data Processing
describes (in words and code) how the data were loaded into R and processed for analysis. 
your analysis must start from the raw CSV file containing the data.
f preprocessing is time-consuming you may consider using the cache = TRUE option for certain code chunks.

## Results
in which your results are presented.

* show the code for your entire analysis. 
* Your analysis can consist of tables, figures, or other summaries. 
* You may use any R package you want to support your analysis.
* Your data analysis must address the following questions:
    *  Across the United States, which types of events (as indicated in the EVTYPE variable) are most harmful with respect to population health?
    * Across the United States, which types of events have the greatest economic consequences?
* Write your report as if it were to be read by a government or municipal manager who isresponsible for preparing for severe weather events and will need to prioritize resources
* no need to make any specific recommendations in your report.
* The analysis document must have at least one figure containing a plot.
* Your analyis must have no more than three figures. Figures may have multiple plots in them (i.e. panel plots), but there cannot be more than three figures total.
